/*bg:[
		"bg/1.png",
		"bg/2.png",
		"bg/3.png",
		"bg/4.png",
		"bg/5.png",
		"bg/6.png",
		"bg/7.png",
		"bg/8.png",
		"bg/9.png",
		"bg/10.png",
		"bg/11.png",
		"bg/12.png",
		"bg/13.png",
		"bg/14.png",
		"bg/15.png",
		"bg/16.png",
		"bg/17.png",
		"bg/18.png",
		"bg/19.png",
		"bg/20.png"
	],*/
//	pano:[
//		"pano/p1-1.png",
//		"pano/p1-2.png",
//		"pano/p2-1.png",
//		"pano/p2-2.png",
//		"pano/p2-3.png",
//		"pano/p3-1.png",
//		"pano/p3-2.png",
//		"pano/p3-3.png",
//		"pano/p3-4.png",
//		"pano/p4-1.png",
//		"pano/p4-2.png",
//		"pano/p4-3.png",
//		"pano/p4-4.png",
//		"pano/p4-5.png",
//		"pano/p5-1.png",
//		"pano/p5-2.png",
//		"pano/p5-3.png",
//		"pano/p5-4.png",
//		"pano/p5-5.png",
//		"pano/p5-6.png",
//		"pano/p6-1.png",
//		"pano/p6-2.png",
//		"pano/p6-3.png",
//		"pano/p6-4.png",
//		"pano/p6-5.png",
//		"pano/p6-6.png",
//		"pano/p7-1.png",
//		"pano/p7-2.png",
//		"pano/p7-3.png",
//		"pano/p8-1.png",
//		"pano/p8-2.png",
//		"pano/p8-3.png",
//		"pano/p8-4.png",
//		"pano/p8-5.png",
//		"pano/p8-6.png"
//	]
var imgData = {
	logo:[
		"load/logo5.png",
		"load/logo5.png",
		"load/logo5.png"
	],
	logoIco:[
		"load/loadIco1.png",
		"load/loadIco2.png",
		"load/loadIco3.png",
		"load/loadIco4.png",
		"load/loadIco5.png",
		"load/loadIco6.png",
		"load/loadIco7.png",
		"load/loadIco8.png",
		"load/loadIco9.png"
	],
	cloud:[
		"bg/cloud1.png",
		"bg/cloud2.png",
		"bg/cloud3.png"
	],
	pageBg:["bg/bg.jpg"],
	bg:[
		"bg/bg-01.jpg",
		"bg/bg-02.jpg",
		"bg/bg-03.jpg",
		"bg/bg-04.jpg",
		"bg/bg-05.jpg",
		"bg/bg-06.jpg",
		"bg/bg-07.jpg",
		"bg/bg-08.jpg",
		"bg/bg-09.jpg",
		"bg/bg-10.jpg",
		"bg/bg-11.jpg",
		"bg/bg-12.jpg",
		"bg/bg-13.jpg",
		"bg/bg-14.jpg",
		"bg/bg-15.jpg",
		"bg/bg-16.jpg",
		"bg/bg-17.jpg",
		"bg/bg-18.jpg",
		"bg/bg-19.jpg",
		"bg/bg-20.jpg"
	],

};